name: movie_catalog
description: Movie catalog is a YIFY (YTS) movie browser

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  connectivity: ^0.4.3+2
  url_launcher: ^5.0.3
  path_provider: ^0.5.0+1
  firebase_messaging: ^5.0.4
  archive: ^2.0.10
  smooth_star_rating: ^1.0.3
  html: ^0.13.4+2
  permission_handler: ^3.1.0
  firebase_admob: ^0.9.0+1
  rxdart: ^0.21.0
  photo_view: ^0.3.3
  sentry: ^2.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1
  debug_mode: ^0.1.1

flutter_icons:
  android: true
  ios: "movie_catalog_icon"
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  adaptive_icon_background: "#FF1E1E24"
  adaptive_icon_foreground: "assets/icon/icon.png"


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/cover_placeholder.jpg
    - assets/images/flag_placeholder.jpg
    - assets/icon/icon.png